image: node:12

pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm run test

  tags:
    src-*:
      - step:
          name: Run tests
          caches:
            - node
          script:
            - npm install
            - npm run test
      - step:
          name: Build and tag built commit
          caches:
            - node
          script:
            - npm install
            - npm run build
            - >
              grep -v dist/ < .gitignore > .gitignore-new
              && mv .gitignore-new .gitignore
              && git add .
              && git commit -m 'adding dist/ via bitbucket-pipelines.yml'
            - >
              tagName=$(echo "$BITBUCKET_TAG" | cut -c 5-);
              [ -n "$BITBUCKET_TAG" ] && echo "Creating: $tagName" || exit 1;
              git tag -a "$tagName" -m "created from $BITBUCKET_TAG"
              && git push origin "$tagName"
