image: node:12

pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm run test

  tags:
    src-*:
      - step:
          name: Run tests
          caches:
            - node
          script:
            - npm install
            - npm run test
      - step:
          name: Build and tag built commit
          caches:
            - node
          script:
            - '[ -n "$BITBUCKET_TAG" ] || exit 1'
            - npm install
            - npm run build
            - >
              grep -v dist/ < .gitignore > .gitignore-new
              && mv .gitignore-new .gitignore
              && git add .
              && git commit -m 'adding dist/ via bitbucket-pipelines.yml'
            - tagName=$(echo "$BITBUCKET_TAG" | cut -c 4-)
            - git tag "$tagName"
            - git push origin "$tagName"
